automation:
  auto_cleanup_enabled: true
  auto_scrape_enabled: false
  backup_enabled: true
  backup_schedule: weekly
  data_retention_days: 30
  scrape_schedule: daily
  scrape_time: 02:00
  validation_enabled: true
database:
  connection_pool_size: 10
  database_name: servicenow_dev
  db_type: postgresql
  echo: false
  host: localhost
  max_overflow: 20
  name: default
  password: ''
  port: 5432
  username: dev_user
logging:
  backup_count: 5
  console_output: true
  file_path: logs/servicenow_docs.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_file_size: 10485760
scraper:
  base_url: https://www.servicenow.com/docs
  chrome_options:
  - --headless
  - --no-sandbox
  - --disable-dev-shm-usage
  - --disable-gpu
  - --window-size=1920,1080
  delay_seconds: 1.0
  discover_links: true
  max_concurrent_requests: 5
  max_pages: 100
  timeout_seconds: 60
  use_selenium: true
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
security:
  allowed_hosts:
  - localhost
  - 127.0.0.1
  api_key_required: true
  enable_ssl: true
  max_requests_per_minute: 60
  rate_limit_enabled: true
servicenow:
  api_version: v2
  instance_url: ''
  max_retries: 3
  password: ''
  timeout: 30
  username: ''
  verify_ssl: true
visualization:
  animation_duration: 1000
  color_scheme: default
  default_layout: spring
  edge_width: 2.0
  enable_interactions: true
  max_nodes_display: 100
  node_size_multiplier: 2.0
